name: cmake-builder/install-dependencies
description: composite and install dependencies

inputs:
  preset:
    description: "cmake preset"
    required: true
  runs-on:
    description: "runs-on for the workflow"
    required: true
  toolchain:
    description: "toolchain to use for building"
    required: true
  auth-service-account:
    description: "service account to use for authenticating against Google Cloud"
    required: true

runs:
  using: composite
  steps:
    - run: |
        mkdir -p ./.selected-dependencies &&
        cat <<EOF >./.selected-dependencies/action.yml
        runs:
          using: composite
          steps:
            - uses: ./.github/actions/runner-setup/${{ inputs.runs-on }}/base
              if: hashFiles('./.github/actions/runner-setup/${{ inputs.runs-on }}/base/action.yml') != ''
              with:
                auth-service-account: ${{inputs.auth-service-account}}

            - uses: ./.github/actions/runner-setup/${{ inputs.runs-on }}/toolchains/${{ inputs.toolchain }}
              if: hashFiles('./.github/actions/runner-setup/${{ inputs.runs-on }}/toolchains/${{ inputs.toolchain }}/action.yml') != ''
              with:
                auth-service-account: ${{inputs.auth-service-account}}

            - uses: ./.github/actions/runner-setup/${{ inputs.runs-on }}/presets/${{ inputs.preset }}
              if: hashFiles('./.github/actions/runner-setup/${{ inputs.runs-on }}/presets/${{ inputs.preset }}/action.yml') != ''
              with:
                auth-service-account: ${{inputs.auth-service-account}}

        EOF
      shell: bash

    - name: install dependencies
      uses: ./.selected-dependencies

    - run: rm -rf ./.selected-dependencies
      if: always()
      shell: bash
