name: cmake-builder/fetch-scripts
description: fetch scripts for cmake-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        repository: tkk2112/cmake-builder
        ref: 0.2.1
        path: ./.cmake-builder
        sparse-checkout: |
          .github/scripts
    - uses: astral-sh/setup-uv@22d500a65c34c827ebc95094040adcee254e92fa
