name: cmake-builder/fetch-scripts
description: fetch scripts for cmake-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: tkk2112/cmake-builder
        ref: 0.2.0
        path: ./.cmake-builder
        sparse-checkout: |
          .github/scripts
    - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
