name: cmake-builder/fetch-scripts
description: fetch scripts for cmake-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      with:
        repository: tkk2112/cmake-builder
        ref: 0.2.1
        path: ./.cmake-builder
        sparse-checkout: |
          .github/scripts
    - uses: astral-sh/setup-uv@b7bf78939d77607a9ccb489e4ec4651ba1092d5c
