name: cmake-builder/fetch-scripts
description: fetch scripts for cmake-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        repository: tkk2112/cmake-builder
        ref: 0.2.1
        path: ./.cmake-builder
        sparse-checkout: |
          .github/scripts
    - uses: astral-sh/setup-uv@085087a5d3dc70f4748c8f303cc8a03e3c7d33df
