name: cmake-builder/fetch-scripts
description: fetch scripts for cmake-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        repository: tkk2112/cmake-builder
        ref: 0.2.0
        path: ./.cmake-builder
        sparse-checkout: |
          .github/scripts
    - uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
