name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-scripts:
    name: Test Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: 3.11
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-5|${{ hashFiles('uv.lock') }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: uv run alias check
      - run: uv run alias test

  test-workflow:
    name: Test Workflow
    uses: ./.github/workflows/cmake-builder.yml
    with:
      runs-on: ubuntu-latest
      toolchain: gcc
      cmake_project_root: ./tests
      presets: |
        {
          "debug": {},
          "release": { "artifact": { "retention_days": 1 }}
        }

  test:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test-scripts, test-workflow]
    steps:
      - run: exit 1
        if: ${{ contains(toJSON(needs.*.result), 'failure') || contains(toJSON(needs.*.result), 'cancelled') }}
